import Head from "next/head";

function news() {
  return (
    <>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>News</h1>
      </div>
    </>
  );
}

export default news;
